name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
      DOCKER_IMAGE: gaganr31/api-app
      EXTERNAL_IP: "146.190.9.118"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Read version from file
      id: read_version
      run: echo "::set-output name=version::$(cat version.txt)"

    - name: Increment version
      id: increment_version
      run: echo $((($(echo "${{ steps.read_version.outputs.version }}" | tr '.' '\n' | tail -n 1) + 1))) > version.txt

    - name: Get commit SHA
      id: commit_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t gaganr31/api-app:${{ steps.read_version.outputs.version }} .
        echo "Built Docker image: gaganr31/api-app:${{ steps.read_version.outputs.version }}"  # Print full Docker image name with tag
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker push gaganr31/api-app:${{ steps.read_version.outputs.version }}
